import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'
import Header from '../components/header'
import react from 'react'
import styled from 'styled-components'
import Text from '../components/text'
import Body from '../components/body'

const MapCont = styled.div`
  
`

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const style = {color:"black"}
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
    
      
      <main className={styles.main}>
        
        <Map/>
        <div>
           <h2 style={style}>Expo Line</h2>
           <p style={style}>
           The Expo Line operates two routes:

        Waterfront Station to King George Station (Surrey)

        Waterfront Station to Production Way University Station (Burnaby)

        Transfer to the Millennium Line at the following stations:

        Commercial Broadway Station

        Lougheed Town Centre Station

        Production Way–University Station

        Use Columbia Station to transfer to and from a train going to either King George or Production Way–University.

        Use Waterfront Station to transfer to the Canada Line, SeaBus, or West Coast Express.
              </p>
        </div>
       
        
      </main>
    </>
  )
}
